### ISSUE TITLE
Fehlermeldung AssamblyVersion

### ISSUE THREAD

**Issue by MK-NEUKO** [MK-NEUKO/Taschenrechner#1]
@suchja
Hallo Jan,
beim Ändern der Assembly wird folgender Fehler angezeigt.
![grafik](https://user-images.githubusercontent.com/67154322/86498740-9833fd00-bd87-11ea-82c7-878d7c0a7352.png)

**Comment by MK-NEUKO** [comment]
Folgende Änderungen schlägt VS mir vor:
![grafik](https://user-images.githubusercontent.com/67154322/86498889-3627c780-bd88-11ea-99ec-67db82af2e11.png)

**Comment by MK-NEUKO** [comment]
Ich habe es ausprobiert, der Fehler bleibt.

**Comment by MK-NEUKO** [comment]
@suchja, ich habe folgendes herausgefunden.
Diese Beschreibung hat geholfen: https://www.it-swarm.dev/de/c%23/automatische-versionierung-visual-studio-2017-.net-core/831331380/
Ich habe in der Datei "Taschenrechner.csproj" die Zeile ```<Deterministic>true</Deterministic>```in ```<Deterministic>false</Deterministic>```geändert. 
Jetzt funktioniert es, das mit der automatischen Versionierung, hat sich wohl seit VS 2017 geändert.

**Comment by suchja** [comment]
Leider habe ich es nicht schneller geschafft. Wir hatten dieses Thema schon im C# Kurs (du hast den doch auch gekauft, oder?) diskutiert:
https://www.udemy.com/instructor/communication/qa/10908022/detail/
https://www.udemy.com/course/einstieg-in-csharp-software-programmieren-wie-ein-profi/learn/lecture/4365262#questions/5629836

Ich werde nun wirklich eine neue Lektion dazu machen. Die Frage gab es nämlich schon ein paar mal.

**Comment by MK-NEUKO** [comment]
@suchja, ich hab den C# Kurs. Ich weiß nicht warum, ich bin wirklich nicht auf die Idee gekommen, in das Forum bei Udemy im Kurs zu suchen.  Ich habe jetzt immer über GitHup geschriebe, dda ist das wohl in Vergessenheit gerate.  Ok, irgendwann hab ich die Lösung woanders gefunden.

**Comment by suchja** [comment]
Blöd, dass du so lange suchen musstest. Momentan sind meine Antwortzeiten leider zu lang. Ich versuche, dass das zukünftig schneller geht.
